# Application name
spring.application.name=freelancer-management

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/freelancer_db
spring.datasource.username=postgres
spring.datasource.password=RoSe2001#

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable joined inheritance strategy
spring.jpa.properties.hibernate.discriminator.ignore_explicit_for_joined=true